class MqttTransport:
    def __init__(self, settings: Settings): ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def publish_downlink(self, dev_eui: str, payload: bytes) -> None: ...
