class StreamBuffer:
    """Thread-safe FIFO buffer for one receiver."""

    def enqueue(self, packet: Packet) -> None: ...
    def try_flush(self) -> Packet | None: ...
    def has_pending(self) -> bool: ...


class BufferManager:
    """Thread-safe dict of per-receiver StreamBuffers."""

    def get_or_create(self, receiver_eui: str) -> StreamBuffer: ...
    def get_all_active(self) -> list[tuple[str, StreamBuffer]]: ...
